version: 2

models:
  - name: prod_identical_table
    description: Table with identical schema in both datasets

  - name: prod_type_mismatch
    description: Table where column types differ between datasets

  - name: prod_column_diff
    description: Table with different columns between datasets

  - name: prod_prod_only
    description: Table that only exists in production
